jQuery.namespace('ErucaCRM.Messages');
ErucaCRM.Messages = {
Login:{"EmailRequired":"Email is required.","PasswordRequired":"Password is required."},
Registration:{"FirstNameRequired":"First name is required.","LastNameRequired":"Last name is required","EmailRequired":"Email is required.","InvalidEmailAddress":"Invalid email address.","PasswordRequired":"Password is required.","ConfirmPasswordRequired":"Confirm password is required","CompanyNameRequired":"Company name is Required"},
Lead:{"NoLeadFound":"No lead found for the selected status","ConfirmLeadDeleteAction":"Are you sure you want to delete this lead?","LeadRequired":"Please select Lead Name.","FirstNameRequired":"First name is required.","EmailRequired":"Email is required.","InvalidEmailAddress":"Invalid email address."},
Profile:{"NothingToSave":"Oops! nothing to save here.","ProfileSavedSuccess":"Profile Saved Successfully","ConfirmProfileDeletionAction":"Are you sure you want to delete this profile?","ProfileDeletedSuccess":"Profile Deleted Successfully.","ProfileDeletedFailure":"Profile not Deleted.","ProfileNameRequired":"Profile name is required"},
Role:{"CreateRole":"Create New Role","RoleCreated":"Role created successfully.","RoleRequired":"Role name is required","ReplyToRequired":"Reply to is required","RoleDeleted":"Role Deleted Successfully.","RoleNotDeleted":"Role not Deleted.","EditRole":"Edit Role","ConfirmRoleDeleteAction":"Are you sure you want to delete this role?","RoleAlreadyExists":"Role Already Exists."},
User:{"NoUserFound":"No user found for the selected status.","StatusNotUpdated":"User status update was not successful.","ActivateText":"Activate","DeactivateText":"DeActivate","CurrentPasswordRequired":"Please enter current password.","NewPasswordRequired":"Please enter new password.","ConfirmPasswordRequired":"Please enter confirm password.","PasswordMatchRequired":"New password and confirm password should same.","PasswordChangeSuccess":"Your password has been changed.","CurrentPasswordIncorrect":"The current password is incorrect.","ActiveText":"Active","InactiveText":"Inactive","MoreDetailsText":"more details","RowButtonEditText":"Edit","RowButtonDeleteText":"Delete","RowButtonAddText":"Add","RowButtonRemoveText":"Remove","FirstNameRequired":"First name is required.","EmailRequired":"Email is required.","InvalidEmailAddress":"Invalid email address."},
Contact:{"NoRecordFound":"No contact found for the selected filter","TagRequired":"Please enter tags for search.","FirstNameRequired":"First name is required.","EmailRequired":"Email is required.","InvalidEmailAddress":"Invalid email address."},
TaskItem:{"ConfirmTaskDeleteAction":"Are you sure you want to delete this task?","NoTaskFound":"No task found for the selected status.","SubjectNameRequired":"Subject name is required"},
Quote:{"NoQuoteFound":"No quote found.","ConfirmQuoteDeleteAction":"Are you sure you want to delete this Quote?","QuoteDeletedSuccess":"Quote Deleted Successfully.","QuoteDeletedFailure":"Quote not Deleted.","OwnerRequired":"Please select Owner.","SubjectRequired":"Subject is required.","SelectProductAndFillAllField":"please select one product and fill mendatory detail.","SubjectNameRequired":"Subject name is required.","OwnerNameRequired":"Owner name is required.","LeadNameRequired":"Lead name is required.","OwnerId":"Owner","Subject":"Subject","ValidTill":"Valid Till","LeadId":"Lead","Carrier":"Carrier","Description":"Description","Discount":"Discount","TotalAfterDiscount":"Total After Discount","Tax":"Tax","SaleTax":"Sale Tax","Vat":"Vat","Adjustment":"Adjustment","NetTotal":"Net Total","SubTotal":"Sub Total","GrandTotal":"Grand Total","GridHeaderSubject":"Subject","GridHeaderLeadName":"Lead Name","GridHeaderOwnerName":"Owner Name","GridHeaderValidityDate":"Due Date","GridHeaderCarrier":"Carrier","GridHeaderProductName":"Product Name","GridHeaderQtyInStock":"Qty. in Strock","GridHeaderQty":"Qty","GridHeaderListPrice":"List Price","GridHeaderTotal":"Total","GridHeaderUnitPrice":"Unit Price","PageHeaderCreate":"Add Quote","PageHeaderEdit":"Edit Quote","PageHeaderManage":"Manage Quotes","PageHeaderDetail":"Quote Detail","PageSubHeaderQuoteInfo":"Quote Information","PageSubHeaderProductDetails":"Product details","PageSubHeaderDescription":"Description","ButtonCreate":"Create New","ButtonEdit":"Edit","ButtonSave":"Save","ButtonBack":"Back","ButtonDelete":"Delete","ButtonAddProduct":"Add Product","ButtonRemoveProduct":"Remove Product","NoDiscount":"No Discount","PercentOfPrice":"% of Price","FixedPrice":"Fixed Price","Plus":"Plus","Minus":"Minus"},
Product:{"AllFieldRequierd":"Please fill all the field.","UnitPriceNotValid":"Unit Price is not valid.","ProductAddedSuccess":"Product Added Successfully.","ProductRemovedSuccess":"Product Removed Successfully."},
Invoice: { "InvoiceDeletedSuccess": "Invoice  Deleted Successfully.", "InvoiceDeletedFailure": "Invoice not Deleted.", "ConfirmInvoiceDeleteAction": "Are you sure you want to delete this Invoice?", "SubjectNameRequired": "Subject name is required.", "OwnerNameRequired": "Owner name is required.", "LeadNameRequired": "Lead name is required.", "OwnerId": "Owner", "Subject": "Subject", "InvoiceDate": "Invoice  Date", "DueDate": "Due Date", "LeadId": "Lead", "SalesOrderId": "Sales Order", "StatusId": "Status", "Description": "Description", "Terms": "Terms", "OwnerName": "Owner Name", "LeadName": "Lead Name", "Discount": "Discount", "TotalAfterDiscount": "Total After Discount", "Tax": "Tax", "SaleTax": "Sale Tax", "Vat": "Vat", "Adjustment": "Adjustment", "NetTotal": "Net Total", "SubTotal": "Sub Total", "GrandTotal": "Grand Total", "GridHeaderSubject": "Subject", "GridHeaderLeadName": "Lead Name", "GridHeaderOwnerName": "Owner Name", "GridHeaderDueDate": "Due Date", "GridHeaderInvoiceDate": "Invoice Date", "GridHeaderProductName": "Product Name", "GridHeaderQtyInStock": "Qty. in Strock", "GridHeaderQty": "Qty", "GridHeaderListPrice": "List Price", "GridHeaderTotal": "Total", "GridHeaderUnitPrice": "Unit Price", "PageHeaderCreate": "Create Invoice", "PageHeaderEdit": "Edit Invoice", "PageHeaderManage": "Manage Invoice", "PageHeaderDetail": "Invoice Detail", "PageSubHeaderInvoiceInfo": "Invoice Information", "PageSubHeaderProductDetails": "Product details", "PageSubHeaderAddressInfo": "Address Information", "PageSubHeaderDescription": "Description", "PageSubHeaderTermAndConditions": "Term And Conditions", "ButtonCreate": "Create New", "ButtonEdit": "Edit", "ButtonSave": "Save", "ButtonBack": "Back", "ButtonDelete": "Delete", "ButtonAddProduct": "Add Product", "ButtonRemoveProduct": "Remove Product", "NoDiscount": "No Discount", "PercentOfPrice": "% of Price", "FixedPrice": "Fixed Price", "Plus": "Plus", "Minus": "Minus" },
Stage: { "CheckStageOrder": "Stage Order must be between 1 to 100.", "StageFieldRequired": "Please fill all the field.", "StageNameExist": "Stage Name Already Exist.", "StageOrderExist": "Order already exist","StageDragNotification":"(*drag and drop to change the order stages.)" },
SalesOrder:{"ConfirmSalesOrderDeleteAction":"Are you sure you want to delete this Sales Order?","SalesOrderDeletedSuccess":"Sales Order Deleted Successfully.","SalesOrderDeletedFailure":"Sales Order not Deleted.","NoSalesOrderFound":"No sale order found","SubjectNameRequired":"Subject name is required.","OwnerNameRequired":"Owner name is required.","LeadNameRequired":"Lead name is required.","OwnerId":"Owner","LeadId":"Lead","Subject":"Subject","DueDate":"Due Date","QuoteId":"Quote","Carrier":"Carrier","SalesCommission":"Sales Commission","Description":"Description","Discount":"Discount","TotalAfterDiscount":"Total After Discount","Tax":"Tax","SaleTax":"Sale Tax","Vat":"Vat","Adjustment":"Adjustment","NetTotal":"Net Total","SubTotal":"Sub Total","GrandTotal":"Grand Total","GridHeaderSubject":"Subject","GridHeaderLeadName":"Lead Name","GridHeaderOwnerName":"Owner Name","GridHeaderValidityDate":"Due Date","GridHeaderCarrier":"Carrier","GridHeaderProductName":"Product Name","GridHeaderQtyInStock":"Qty. in Strock","GridHeaderQty":"Qty","GridHeaderListPrice":"List Price","GridHeaderTotal":"Total","GridHeaderUnitPrice":"Unit Price","PageSubHeaderSaleOrderInfo":"Sale Order Information","PageSubHeaderProductDetails":"Product details","PageSubHeaderDescription":"Description","PageSubHeaderAddressInfo":"Address Information","PageHeaderCreate":"Create Sale Order","PageHeaderEdit":"Edit Sale Order","PageHeaderManage":"Manage Sale Orders","PageHeaderDetail":"Sale Order Detail","ButtonCreate":"Create New","ButtonEdit":"Edit","ButtonSave":"Save","ButtonBack":"Back","ButtonDelete":"Delete","ButtonAddProduct":"Add Product","ButtonRemoveProduct":"Remove Product","NoDiscount":"No Discount","PercentOfPrice":"% of Price","FixedPrice":"Fixed Price","Plus":"Plus","Minus":"Minus"},
Document:{"ConfirmDocumentDeleteAction":"Are you sure you want to delete this document from attachment?","DocumentRemoved":"Document Removed Successfully.","DocumentNotRemoved":"Document Not Removed"},
Address:{},
Layout:{},
LayoutInner:{},
DashBoard:{}
}