//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountContacts = new HashSet<AccountContact>();
            this.AccountTags = new HashSet<AccountTag>();
            this.AccountCases = new HashSet<AccountCase>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.FileAttachments = new HashSet<FileAttachment>();
            this.Leads = new HashSet<Lead>();
        }
    
        public int AccountId { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> ParentAccountId { get; set; }
        public int AccountOwnerId { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public Nullable<int> NumberOfEmployee { get; set; }
        public string AccountLocation { get; set; }
        public string AccountWebsite { get; set; }
        public string EmailId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> AnnualRevenue { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> BillingAddressId { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Company Company { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual ICollection<AccountContact> AccountContacts { get; set; }
        public virtual ICollection<AccountTag> AccountTags { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<AccountCase> AccountCases { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
    }
}
