//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCase
    {
        public AccountCase()
        {
            this.CaseMessageBoards = new HashSet<CaseMessageBoard>();
            this.FileAttachments = new HashSet<FileAttachment>();
        }
    
        public int AccountCaseId { get; set; }
        public string CaseNumber { get; set; }
        public Nullable<int> AccountId { get; set; }
        public int CaseOwnerId { get; set; }
        public int CaseOriginId { get; set; }
        public string Subject { get; set; }
        public int CaseTypeId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CaseMessageBoard> CaseMessageBoards { get; set; }
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
    }
}
