//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationPage
    {
        public ApplicationPage()
        {
            this.AssociationApplicationPages = new HashSet<AssociationApplicationPage>();
            this.AssociationApplicationPages1 = new HashSet<AssociationApplicationPage>();
            this.ContentApplicationPages = new HashSet<ContentApplicationPage>();
        }
    
        public int ApplicationPageId { get; set; }
        public string PageTitle { get; set; }
        public string PageDescription { get; set; }
        public string PageUrl { get; set; }
        public bool IsApplicationPage { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
    
        public virtual ICollection<AssociationApplicationPage> AssociationApplicationPages { get; set; }
        public virtual ICollection<AssociationApplicationPage> AssociationApplicationPages1 { get; set; }
        public virtual ICollection<ContentApplicationPage> ContentApplicationPages { get; set; }
    }
}
