//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationApplicationPage
    {
        public int AssociationApplicationPageId { get; set; }
        public int ApplicationPageId { get; set; }
        public int CustomPageId { get; set; }
    
        public virtual ApplicationPage ApplicationPage { get; set; }
        public virtual ApplicationPage ApplicationPage1 { get; set; }
    }
}
