//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociatedProduct
    {
        public AssociatedProduct()
        {
            this.ProductInvoiceAssociations = new HashSet<ProductInvoiceAssociation>();
            this.ProductQuoteAssociations = new HashSet<ProductQuoteAssociation>();
            this.ProductSalesOrderAssociations = new HashSet<ProductSalesOrderAssociation>();
        }
    
        public int AssociatedProductId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> QtyInStock { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<bool> TaxApplied { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<bool> VatApplied { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductInvoiceAssociation> ProductInvoiceAssociations { get; set; }
        public virtual ICollection<ProductQuoteAssociation> ProductQuoteAssociations { get; set; }
        public virtual ICollection<ProductSalesOrderAssociation> ProductSalesOrderAssociations { get; set; }
    }
}
