//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseMessageBoard
    {
        public CaseMessageBoard()
        {
            this.FileAttachments = new HashSet<FileAttachment>();
        }
    
        public int CaseMessageBoardId { get; set; }
        public int AccountCaseId { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual AccountCase AccountCase { get; set; }
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
    }
}
