//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Roles = new HashSet<Role>();
            this.Ratings = new HashSet<Rating>();
            this.CompanyPlans = new HashSet<CompanyPlan>();
            this.Accounts = new HashSet<Account>();
            this.Users = new HashSet<User>();
            this.Stages = new HashSet<Stage>();
            this.Profiles = new HashSet<Profile>();
            this.Tags = new HashSet<Tag>();
            this.RealTimeNotificationConnections = new HashSet<RealTimeNotificationConnection>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public bool IsActive { get; set; }
        public bool RecordDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<CompanyPlan> CompanyPlans { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<RealTimeNotificationConnection> RealTimeNotificationConnections { get; set; }
    }
}
