//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactTags = new HashSet<ContactTag>();
            this.Invoices = new HashSet<Invoice>();
            this.ProductContactAssociations = new HashSet<ProductContactAssociation>();
            this.Quotes = new HashSet<Quote>();
            this.AccountContacts = new HashSet<AccountContact>();
            this.LeadContacts = new HashSet<LeadContact>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.FileAttachments = new HashSet<FileAttachment>();
            this.Leads = new HashSet<Lead>();
        }
    
        public int ContactId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> LeadSourceId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailAddress { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string HomePhone { get; set; }
        public string OtherPhone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Department { get; set; }
        public string ContactCompanyName { get; set; }
        public string Assistant { get; set; }
        public string ReportsTo { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string AsstPhone { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
        public string Tags { get; set; }
        public Nullable<int> LeadId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string JobPosition { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<ContactTag> ContactTags { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ProductContactAssociation> ProductContactAssociations { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<AccountContact> AccountContacts { get; set; }
        public virtual ICollection<LeadContact> LeadContacts { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
    }
}
