//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CultureInformation
    {
        public CultureInformation()
        {
            this.ContentApplicationPages = new HashSet<ContentApplicationPage>();
            this.Users = new HashSet<User>();
        }
    
        public int CultureInformationId { get; set; }
        public string CultureName { get; set; }
        public string Language { get; set; }
        public string ExcelFilePath { get; set; }
        public string LabelsXML { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
        public string LangDirection_ { get; set; }
        public string IconPath { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual ICollection<ContentApplicationPage> ContentApplicationPages { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
