//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttachment
    {
        public long DocumentId { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> AttachedBy { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LeadId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> CaseMessageBoardId { get; set; }
        public Nullable<int> AccountCaseId { get; set; }
        public bool RecordDeleted { get; set; }
        public string FileDuration { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountCase AccountCase { get; set; }
        public virtual CaseMessageBoard CaseMessageBoard { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual User User { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual TaskItem TaskItem { get; set; }
    }
}
