//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadAudit
    {
        public int LeadAuditId { get; set; }
        public Nullable<int> LeadId { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> RatingId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<int> ActivityType { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
