//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadComment
    {
        public int LeadCommentId { get; set; }
        public string Comment { get; set; }
        public int LeadId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AudioFileName { get; set; }
        public string AudioFileDuration { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual User User { get; set; }
    }
}
