//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public Lead()
        {
            this.FileAttachments = new HashSet<FileAttachment>();
            this.Invoices = new HashSet<Invoice>();
            this.LeadContacts = new HashSet<LeadContact>();
            this.LeadTags = new HashSet<LeadTag>();
            this.ProductLeadAssociations = new HashSet<ProductLeadAssociation>();
            this.Quotes = new HashSet<Quote>();
            this.LeadAudits = new HashSet<LeadAudit>();
            this.LeadComments = new HashSet<LeadComment>();
        }
    
        public int LeadId { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> RatingId { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> LeadOwnerId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string Title { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public string Phone { get; set; }
        public string LeadCompanyName { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> LeadSourceId { get; set; }
        public Nullable<int> LeadStatusId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string Description { get; set; }
        public int CompanyId { get; set; }
        public bool IsLeadConvertedToAccount { get; set; }
        public bool IsLeadCreatedFromAccount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<bool> IsClosedWin { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileDuration { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual LeadSource LeadSource { get; set; }
        public virtual LeadStatu LeadStatu { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LeadContact> LeadContacts { get; set; }
        public virtual ICollection<LeadTag> LeadTags { get; set; }
        public virtual ICollection<ProductLeadAssociation> ProductLeadAssociations { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<LeadAudit> LeadAudits { get; set; }
        public virtual ICollection<LeadComment> LeadComments { get; set; }
    }
}
