//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadStatus
    {
        public LeadStatus()
        {
            this.Leads = new HashSet<Lead>();
        }
    
        public int LeadStatusId { get; set; }
        public string LeadStatusName { get; set; }
    
        public virtual ICollection<Lead> Leads { get; set; }
    }
}
