//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ModulePermissions = new HashSet<ModulePermission>();
            this.PlanModules = new HashSet<PlanModule>();
            this.TaskItems = new HashSet<TaskItem>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ModuleCONSTANT { get; set; }
        public Nullable<int> ParentModuleId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string RenderType { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsPlanModule { get; set; }
        public bool RecordDeleted { get; set; }
    
        public virtual ICollection<ModulePermission> ModulePermissions { get; set; }
        public virtual ICollection<PlanModule> PlanModules { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<TaskItem> TaskItems { get; set; }
    }
}
