//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanModule
    {
        public int PlanModuleId { get; set; }
        public int PlanId { get; set; }
        public int ModuleId { get; set; }
        public bool HasPermission { get; set; }
        public bool HasPermissionAfterTrail { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
