//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.AssociatedProducts = new HashSet<AssociatedProduct>();
            this.ProductLeadAssociations = new HashSet<ProductLeadAssociation>();
            this.ProductContactAssociations = new HashSet<ProductContactAssociation>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
    
        public virtual ICollection<AssociatedProduct> AssociatedProducts { get; set; }
        public virtual ICollection<ProductLeadAssociation> ProductLeadAssociations { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProductContactAssociation> ProductContactAssociations { get; set; }
    }
}
