//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItem
    {
        public TaskItem()
        {
            this.FileAttachments = new HashSet<FileAttachment>();
        }
    
        public int TaskId { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssociatedModuleId { get; set; }
        public Nullable<int> AssociatedModuleValue { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
        public string AudioFileName { get; set; }
        public string AudioFileDuration { get; set; }
    
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
    }
}
