//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public TimeZone()
        {
            this.Users = new HashSet<User>();
        }
    
        public int TimeZoneId { get; set; }
        public string TimeZone_Location { get; set; }
        public string GMT { get; set; }
        public double offset { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
