//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserSettingId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> MaxLeadAuditId { get; set; }
        public Nullable<int> TotalNotifications { get; set; }
        public Nullable<bool> IsSendNotificationsRecentActivities { get; set; }
        public Nullable<int> SchedulerMaxLeadAuditId { get; set; }
    
        public virtual User User { get; set; }
    }
}
