//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErucaCRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.CaseMessageBoards = new HashSet<CaseMessageBoard>();
            this.Contacts = new HashSet<Contact>();
            this.Invoices = new HashSet<Invoice>();
            this.Modules = new HashSet<Module>();
            this.Modules1 = new HashSet<Module>();
            this.Products = new HashSet<Product>();
            this.ProfilePermissions = new HashSet<ProfilePermission>();
            this.ProfilePermissions1 = new HashSet<ProfilePermission>();
            this.Quotes = new HashSet<Quote>();
            this.AccountCases = new HashSet<AccountCase>();
            this.Profiles = new HashSet<Profile>();
            this.Profiles1 = new HashSet<Profile>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.FileAttachments = new HashSet<FileAttachment>();
            this.Leads = new HashSet<Lead>();
            this.UserSettings = new HashSet<UserSetting>();
            this.TaskItems = new HashSet<TaskItem>();
            this.RealTimeNotificationConnections = new HashSet<RealTimeNotificationConnection>();
            this.LeadComments = new HashSet<LeadComment>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ActivationLinkSentDate { get; set; }
        public string Password { get; set; }
        public string ImageURL { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<System.Guid> ActivationId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
        public Nullable<int> CultureInformationId { get; set; }
        public Nullable<int> TimezoneId { get; set; }
        public string TokenId { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<CaseMessageBoard> CaseMessageBoards { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual CultureInformation CultureInformation { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Module> Modules1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProfilePermission> ProfilePermissions { get; set; }
        public virtual ICollection<ProfilePermission> ProfilePermissions1 { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual Role Role { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual ICollection<AccountCase> AccountCases { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Profile> Profiles1 { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<FileAttachment> FileAttachments { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<UserSetting> UserSettings { get; set; }
        public virtual ICollection<TaskItem> TaskItems { get; set; }
        public virtual ICollection<RealTimeNotificationConnection> RealTimeNotificationConnections { get; set; }
        public virtual ICollection<LeadComment> LeadComments { get; set; }
    }
}
